const fs = require('fs');

const adminEn = {
  "dashboard": "Dashboard",
  "orders": "Orders",
  "customOrders": "Custom Designs",
  "products": "Products",
  "categories": "Categories",
  "users": "Users",
  "settings": "Settings",
  "switchLanguage": "Switch Language",
  "systemOverview": "System Overview",
  "totalRevenue": "Total Revenue",
  "standardOrders": "Standard Orders",
  "customAiOrders": "Custom AI Orders",
  "totalUsers": "Total Users",
  "recentStandardOrders": "Recent Standard Orders",
  "customer": "Customer",
  "amount": "Amount",
  "status": "Status",
  "unknown": "Unknown",
  "noStandardOrders": "No standard orders yet.",
  "recentCustomDesigns": "Recent Custom AI Designs",
  "aiPreview": "AI Preview",
  "noImage": "No image",
  "noCustomDesigns": "No custom designs uploaded yet.",
  "manageOrders": "Manage Orders",
  "tabAll": "All",
  "tabPending": "Pending",
  "tabProcessing": "Processing",
  "tabShipped": "Shipped",
  "tabDelivered": "Delivered",
  "tabCancelled": "Cancelled",
  "date": "Date",
  "total": "Total",
  "payment": "Payment",
  "actions": "Actions",
  "viewDetails": "View Details",
  "noOrdersFoundFor": "No standard orders found for",
  "manageCustomOrders": "Manage Custom AI Orders",
  "tabManufacturing": "Manufacturing",
  "tabRejected": "Rejected",
  "orderId": "Order ID",
  "prompt": "Prompt",
  "preview": "Preview",
  "price": "Price",
  "approve": "Approve",
  "reject": "Reject",
  "noneText": "None",
  "tbd": "TBD",
  "tabPendingReview": "Pending Review",
  "tabConfirmed": "Confirmed",
  "orderDetails": "Order Details:",
  "designSpecs": "Design Specifications",
  "userUploadLogo": "User Upload (Logo):",
  "colorsText": "Colors:",
  "noColors": "No colors selected",
  "shippingCustomer": "Shipping & Customer",
  "shippingAddressText": "Shipping Address:",
  "pricingActions": "Pricing & Actions",
  "currentStatus": "Current Status:",
  "totalPriceText": "Total Price:",
  "setFinalPrice": "Set Final Price & Approve",
  "closeView": "Close View",
  "manageProducts": "Manage Products",
  "addProduct": "Add Product",
  "editProduct": "Edit Product",
  "addNewProduct": "Add New Product",
  "productName": "Product Name *",
  "priceUsd": "Price (USD) *",
  "stockQuantity": "Stock Quantity",
  "categoryStar": "Category *",
  "selectCategory": "Select a category...",
  "descriptionStar": "Description *",
  "describeProduct": "Describe this product...",
  "availableSizes": "Available Sizes",
  "typeSize": "Type a size (e.g. S, XL) and press Enter or Add",
  "addBtn": "Add",
  "colorsLabel": "Colors",
  "productImages": "Product Images",
  "clickUpload": "Click to upload images",
  "imageFormats": "PNG, JPG or WebP (Max 5 images)",
  "featuredProduct": "Featured Product (shows on homepage)",
  "updateProduct": "Update Product",
  "createProduct": "Create Product",
  "productTh": "Product",
  "categoryTh": "Category",
  "stockTh": "Stock",
  "editBtn": "Edit",
  "deleteBtn": "Delete",
  "inStock": "in stock",
  "outOfStock": "Out of stock",
  "featuredBadge": "Featured",
  "noProductsYet": "No products yet. Click 'Add Product' to get started.",
  "usersRoles": "Users & Roles",
  "createAccount": "Create Account",
  "createNewAccount": "Create New Account",
  "fullName": "Full Name",
  "email": "Email",
  "password": "Password",
  "role": "Role",
  "userTh": "User",
  "joined": "Joined",
  "noUsersYet": "No users in the database yet.",
  "createFirstAdmin": "Create the first admin ->",
  "newCategory": "New Category",
  "editCategory": "Edit Category",
  "categoryName": "Category Name *",
  "parentCategory": "Parent Category (optional)",
  "updateCategory": "Update Category",
  "createCategory": "Create Category",
  "nameTh": "Name",
  "slugTh": "Slug",
  "parentTh": "Parent",
  "sure": "Sure?",
  "yesDelete": "Yes, Delete",
  "cancel": "Cancel",
  "noCategories": "No categories yet. Create your first one!",
  "platformSettings": "Platform Settings",
  "paymentGateway": "Payment Gateway Configurations",
  "instaPay": "InstaPay Number / Handle",
  "walletNumber": "Mobile Wallet Number",
  "bankAccount": "Bank Account Details (IBAN)",
  "acceptManual": "Accept Manual Transfers",
  "saveSettings": "Save Settings"
};

const adminAr = {
  "dashboard": "لوحة القيادة",
  "orders": "الطلبات",
  "customOrders": "تصاميم مخصصة",
  "products": "المنتجات",
  "categories": "التصنيفات",
  "users": "المستخدمين",
  "settings": "الإعدادات",
  "switchLanguage": "تغيير اللغة",
  "systemOverview": "نظرة عامة على النظام",
  "totalRevenue": "إجمالي الإيرادات",
  "standardOrders": "الطلبات العادية",
  "customAiOrders": "طلبات الذكاء",
  "totalUsers": "عدد المستخدمين",
  "recentStandardOrders": "أحدث الطلبات العادية",
  "customer": "العميل",
  "amount": "المبلغ",
  "status": "الحالة",
  "unknown": "غير معروف",
  "noStandardOrders": "لا توجد طلبات عادية بعد.",
  "recentCustomDesigns": "أحدث تصاميم الذكاء الاصطناعي",
  "aiPreview": "معاينة",
  "noImage": "لا توجد صورة",
  "noCustomDesigns": "لم يتم رفع تصاميم مخصصة بعد.",
  "manageOrders": "إدارة الطلبات",
  "tabAll": "الكل",
  "tabPending": "قيد الانتظار",
  "tabProcessing": "قيد المعالجة",
  "tabShipped": "تم الشحن",
  "tabDelivered": "مُسلّم",
  "tabCancelled": "ملغى",
  "date": "التاريخ",
  "total": "الإجمالي",
  "payment": "الدفع",
  "actions": "إجراءات",
  "viewDetails": "عرض التفاصيل",
  "noOrdersFoundFor": "لا توجد طلبات عادية لهذه الحالة:",
  "manageCustomOrders": "إدارة طلبات التصاميم المخصصة",
  "tabManufacturing": "قيد التصنيع",
  "tabRejected": "مرفوض",
  "orderId": "رقم الطلب",
  "prompt": "الوصف",
  "preview": "معاينة",
  "price": "السعر",
  "approve": "موافقة",
  "reject": "رفض",
  "noneText": "لا يوجد",
  "tbd": "لم يحدد بعد",
  "tabPendingReview": "انتظار المراجعة",
  "tabConfirmed": "مؤكد",
  "orderDetails": "تفاصيل الطلب:",
  "designSpecs": "مواصفات التصميم",
  "userUploadLogo": "رفع المستخدم (شعار):",
  "colorsText": "الألوان:",
  "noColors": "لم يتم اختيار ألوان",
  "shippingCustomer": "الشحن وبيانات العميل",
  "shippingAddressText": "عنوان الشحن:",
  "pricingActions": "التسعير والإجراءات",
  "currentStatus": "الحالة الحالية:",
  "totalPriceText": "السعر الإجمالي:",
  "setFinalPrice": "تحديد السعر النهائي والموافقة",
  "closeView": "إغلاق العرض",
  "manageProducts": "إدارة المنتجات",
  "addProduct": "إضافة منتج",
  "editProduct": "تعديل المنتج",
  "addNewProduct": "إضافة منتج جديد",
  "productName": "اسم المنتج *",
  "priceUsd": "السعر (دولار) *",
  "stockQuantity": "كمية المخزون",
  "categoryStar": "التصنيف *",
  "selectCategory": "اختر تصنيفاً...",
  "descriptionStar": "الوصف *",
  "describeProduct": "صف هذا المنتج...",
  "availableSizes": "المقاسات المتاحة",
  "typeSize": "اكتب مقاساً (مثل S, XL) واضغط إدخال أو أضف",
  "addBtn": "أضف",
  "colorsLabel": "الألوان",
  "productImages": "صور المنتج",
  "clickUpload": "انقر لرفع الصور",
  "imageFormats": "PNG أو JPG أو WebP (بحد أقصى 5 صور)",
  "featuredProduct": "منتج مميز (يظهر في الصفحة الرئيسية)",
  "updateProduct": "تحديث المنتج",
  "createProduct": "إنشاء منتج",
  "productTh": "المنتج",
  "categoryTh": "التصنيف",
  "stockTh": "المخزون",
  "editBtn": "تعديل",
  "deleteBtn": "حذف",
  "inStock": "في المخزن",
  "outOfStock": "نفذت الكمية",
  "featuredBadge": "مميز",
  "noProductsYet": "لا توجد منتجات بعد. انقر على 'إضافة منتج' للبدء.",
  "usersRoles": "المستخدمون والأدوار",
  "createAccount": "إنشاء حساب",
  "createNewAccount": "إنشاء حساب جديد",
  "fullName": "الاسم الكامل",
  "email": "البريد الإلكتروني",
  "password": "كلمة المرور",
  "role": "الدور",
  "userTh": "المستخدم",
  "joined": "تاريخ الانضمام",
  "noUsersYet": "لا يوجد مستخدمون في قاعدة البيانات بعد.",
  "createFirstAdmin": "إنشاء أول مشرف ->",
  "newCategory": "تصنيف جديد",
  "editCategory": "تعديل التصنيف",
  "categoryName": "اسم التصنيف *",
  "parentCategory": "التصنيف الأعلى (اختياري)",
  "updateCategory": "تحديث التصنيف",
  "createCategory": "إنشاء تصنيف",
  "nameTh": "الاسم",
  "slugTh": "الرابط",
  "parentTh": "الأعلى",
  "sure": "متأكد؟",
  "yesDelete": "نعم، احذف",
  "cancel": "إلغاء",
  "noCategories": "لا توجد تصنيفات بعد. أنشئ تصنيفك الأول!",
  "platformSettings": "إعدادات المنصة",
  "paymentGateway": "إعدادات بوابات الدفع",
  "instaPay": "رقم / عنوان إنستا باي",
  "walletNumber": "رقم المحفظة الإلكترونية",
  "bankAccount": "تفاصيل الحساب البنكي (IBAN)",
  "acceptManual": "قبول التحويلات اليدوية",
  "saveSettings": "حفظ الإعدادات"
};


// Update english
let enPath = './src/lib/i18n/dictionaries/en.json';
let enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));
enData.admin = adminEn;

if(!enData.nav) enData.nav = {};
enData.nav.switchLang = "Switch Language";
if(!enData.footer) enData.footer = {};
enData.footer.rights = "DS Fashion. All rights reserved.";

fs.writeFileSync(enPath, JSON.stringify(enData, null, 2));

// Update arabic
let arPath = './src/lib/i18n/dictionaries/ar.json';
let arData = JSON.parse(fs.readFileSync(arPath, 'utf8'));
arData.admin = adminAr;

if(!arData.nav) arData.nav = {};
arData.nav.switchLang = "تغيير اللغة";
if(!arData.footer) arData.footer = {};
arData.footer.rights = "أزياء دي إس. جميع الحقوق محفوظة.";

fs.writeFileSync(arPath, JSON.stringify(arData, null, 2));
console.log("Successfully updated dictionaries.");
